export const LOAD_GROUPSDATA_REQUEST = 'LOAD_GROUPSDATA_REQUEST'
export const LOAD_GROUPSDATA_SUCCESS = 'LOAD_GROUPSDATA_SUCCESS'
export const LOAD_GROUPSDATA_FAILURE = 'LOAD_GROUPSDATA_FAILURE'

export const UPDATE_GROUPSDATA_REQUEST = 'UPDATE_GROUPSDATA_REQUEST'
export const UPDATE_GROUPSDATA_SUCCESS = 'UPDATE_GROUPSDATA_SUCCESS'
export const UPDATE_GROUPSDATA_FAILURE = 'UPDATE_GROUPSDATA_FAILURE'